## Readme - Human Activity Recognition using Smartphones Data Set

The dataset for the coursera project is taken from the www.smartlab.ws. A group of 30 volunteers between the age bracket of 19-48 years performed six activities (walking, walking upstairs, walking downstairs, sitting, standing and laying) wearing a smartphone on the waist. The smartphone has an embedded accelerometer and gyroscope which is used to capture 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The dataset is partitioned into two sets; training data and test data.

The objective of the project is to create a tidy dataset (combining train set and test set), extract only column names with mean() and std() and calculate the average of each variable for each activity and each subject.

The steps taken to create a tidy dataset and object definition are explained in codebook.

**The dataset includes the following files:**

* activity_original.txt: List of activity labels (original file from UCI)
* Codebook.html and Codebook.Rmd: Dataset codebook (created for the coursera project)
* features_info.txt: Detail of variables used on the feature vector (original file from UCI)
* features.txt: Features list (original file from UCI)
* README_original.txt: (original file from UCI)
* Readme.html and Readme.Rmd: Readme (created for the coursera project)
* run_analysis.R: Script of the tidy data set
* tidy_dataset.txt: Tidy data with the average of each variable for each activity and each subject
* train/X_train.txt: Training set (original file from UCI)
* train/y_train.txt: Training labels (original file from UCI)
* test/X_test.txt: Test set (original file from UCI)
* test/y_test.txt: Test labels (original file from UCI)
* train/subject_train.txt: Experiments are performed by humans and differentiated by subject ID
Following files are not used in creating of a tidy data set:
* Files under test/Inertial Signals and train/Inertial Signals directories are not used

**Reference**

The dataset is taken from the following source:

Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

**---End of readme---**